--Scripts que voy a hacer a cada rato
SET SERVEROUTPUT ON;
EXECUTE CADENA_INFECCION (1, 1, '19/06/2020', '29/06/2020');

-- Selects
SELECT * FROM INFECTADOS_COVID;
SELECT i.id_persona, i.HIST.FEC_I FROM INFECTADOS_COVID i;

-- Delete
DELETE FROM INFECTADOS_COVID WHERE ID > 4;