/* Inserts */
/*Para las imagenes debemos establecer las rutas*/
CREATE  DIRECTORY DIR_BANDERAS AS 'C:\img_proyecto\flags';
CREATE  DIRECTORY DIR_PROV AS 'C:\img_proyecto\prov';
CREATE  DIRECTORY DIR_PEOPLE AS 'C:\img_proyecto\people';
CREATE  DIRECTORY DIR_AIRLINES AS 'C:\img_proyecto\airlines';

/* TABLE patologias */
INSERT INTO patologias VALUES (id_patologia_seq.nextval, 'Asma');
INSERT INTO patologias VALUES (id_patologia_seq.nextval, 'Bronquitis');
INSERT INTO patologias VALUES (id_patologia_seq.nextval, 'Bulimia');
INSERT INTO patologias VALUES (id_patologia_seq.nextval, 'Cancer');
INSERT INTO patologias VALUES (id_patologia_seq.nextval, 'Dengue');
INSERT INTO patologias VALUES (id_patologia_seq.nextval, 'Endocarditis');
INSERT INTO patologias VALUES (id_patologia_seq.nextval, 'Faringitis');
INSERT INTO patologias VALUES (id_patologia_seq.nextval, 'Glaucoma');
INSERT INTO patologias VALUES (id_patologia_seq.nextval, 'Gripe');
INSERT INTO patologias VALUES (id_patologia_seq.nextval, 'Insuficiencia cardiaca');
INSERT INTO patologias VALUES (id_patologia_seq.nextval, 'Neumonia');
INSERT INTO patologias VALUES (id_patologia_seq.nextval, 'Obesidad');
INSERT INTO patologias VALUES (id_patologia_seq.nextval, 'Pariotiditis');
INSERT INTO patologias VALUES (id_patologia_seq.nextval, 'Parkinson');
INSERT INTO patologias VALUES (id_patologia_seq.nextval, 'Rinitis');
INSERT INTO patologias VALUES (id_patologia_seq.nextval, 'Rotavitus');
INSERT INTO patologias VALUES (id_patologia_seq.nextval, 'Sarampión');
INSERT INTO patologias VALUES (id_patologia_seq.nextval, 'Sarcoidosis');
INSERT INTO patologias VALUES (id_patologia_seq.nextval, 'Sífilis');
INSERT INTO patologias VALUES (id_patologia_seq.nextval, 'Toxoplasmosis');
INSERT INTO patologias VALUES (id_patologia_seq.nextval, 'Urticaria');
INSERT INTO patologias VALUES (id_patologia_seq.nextval, 'Varicela');
INSERT INTO patologias VALUES (id_patologia_seq.nextval, 'Vasculitis');

/* TABLE sintomas */
INSERT INTO sintomas VALUES (id_sintoma_seq.nextval, 'Cansancio');
INSERT INTO sintomas VALUES (id_sintoma_seq.nextval, 'Conjuntivitis');
INSERT INTO sintomas VALUES (id_sintoma_seq.nextval, 'Diarrea');
INSERT INTO sintomas VALUES (id_sintoma_seq.nextval, 'Dificultad para despertarse o permanecer despierto');
INSERT INTO sintomas VALUES (id_sintoma_seq.nextval, 'Dificultad respiratoria');
INSERT INTO sintomas VALUES (id_sintoma_seq.nextval, 'Dolor de garganta');
INSERT INTO sintomas VALUES (id_sintoma_seq.nextval, 'Dolor muscular');
INSERT INTO sintomas VALUES (id_sintoma_seq.nextval, 'Dolor o presíon en el pecho');
INSERT INTO sintomas VALUES (id_sintoma_seq.nextval, 'Erupciones cutáneas');
INSERT INTO sintomas VALUES (id_sintoma_seq.nextval, 'Escalofríos');
INSERT INTO sintomas VALUES (id_sintoma_seq.nextval, 'Fiebre');
INSERT INTO sintomas VALUES (id_sintoma_seq.nextval, 'Incapacidad para hablar');
INSERT INTO sintomas VALUES (id_sintoma_seq.nextval, 'Molestias y dolores');
INSERT INTO sintomas VALUES (id_sintoma_seq.nextval, 'Nauseas o vómitos');
INSERT INTO sintomas VALUES (id_sintoma_seq.nextval, 'Perdida de color en las manos');
INSERT INTO sintomas VALUES (id_sintoma_seq.nextval, 'Perdida del sentido del gusto');
INSERT INTO sintomas VALUES (id_sintoma_seq.nextval, 'Perdida del sentido del olfato');
INSERT INTO sintomas VALUES (id_sintoma_seq.nextval, 'Tos seca');
/
/* TABLE proveedores 
   Hay que hacerlo con un bloque anonimo para que se inserten las imagenes*/
DECLARE 
  v_blob BLOB;
  v_bfile BFILE;
BEGIN
    INSERT INTO proveedores VALUES (id_proveedor_seq.nextval, 'AOL', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_PROV', 'aol.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO proveedores VALUES (id_proveedor_seq.nextval, 'AT&.T', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_PROV', 'atyt.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO proveedores VALUES (id_proveedor_seq.nextval, 'CANTV', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_PROV', 'cantv.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO proveedores VALUES (id_proveedor_seq.nextval, 'Claro', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_PROV', 'claro.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO proveedores VALUES (id_proveedor_seq.nextval, 'Clearwire', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_PROV', 'clearwire.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO proveedores VALUES (id_proveedor_seq.nextval, 'Entel', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_PROV', 'entel.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO proveedores VALUES (id_proveedor_seq.nextval, 'Movistar', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_PROV', 'movistar.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO proveedores VALUES (id_proveedor_seq.nextval, 'Orange', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_PROV', 'orange.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO proveedores VALUES (id_proveedor_seq.nextval, 'Singapur Telecomunicaciones', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_PROV', 'singtel.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO proveedores VALUES (id_proveedor_seq.nextval, 'Speedy', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_PROV', 'speedy.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO proveedores VALUES (id_proveedor_seq.nextval, 'Starlink', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_PROV', 'starlink.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO proveedores VALUES (id_proveedor_seq.nextval, 'Telmex', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_PROV', 'telmex.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO proveedores VALUES (id_proveedor_seq.nextval, 'UUnet', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_PROV', 'uunet.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO proveedores VALUES (id_proveedor_seq.nextval, 'Verizon', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_PROV', 'verizon.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO proveedores VALUES (id_proveedor_seq.nextval, 'VTR', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_PROV', 'vtr.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
END;
/
/* TABLE aerolineas
   Hay que hacerlo con un bloque anonimo para que se inserten las imagenes*/
DECLARE 
  v_blob BLOB;
  v_bfile BFILE;
BEGIN
    INSERT INTO aerolineas VALUES (id_aerolinea_seq.nextval, 'Allegiant Air', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_AIRLINES', 'allegiant.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO aerolineas VALUES (id_aerolinea_seq.nextval, 'Air France', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_AIRLINES', 'airfrance.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO aerolineas VALUES (id_aerolinea_seq.nextval, 'American Airlines', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_AIRLINES', 'american_airlines.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO aerolineas VALUES (id_aerolinea_seq.nextval, 'Avianca', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_AIRLINES', 'avianca.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO aerolineas VALUES (id_aerolinea_seq.nextval, 'Avior Airlines', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_AIRLINES', 'avior.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO aerolineas VALUES (id_aerolinea_seq.nextval, 'Conviasa', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_AIRLINES', 'conviasa.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO aerolineas VALUES (id_aerolinea_seq.nextval, 'Grupo Lufthansa', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_AIRLINES', 'lufthansa.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO aerolineas VALUES (id_aerolinea_seq.nextval, 'Delta Air Lines', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_AIRLINES', 'delta.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO aerolineas VALUES (id_aerolinea_seq.nextval, 'Estelar', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_AIRLINES', 'estelar.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO aerolineas VALUES (id_aerolinea_seq.nextval, 'Frointer Airlines', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_AIRLINES', 'frontier.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO aerolineas VALUES (id_aerolinea_seq.nextval, 'Laser Airlines', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_AIRLINES', 'laser.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO aerolineas VALUES (id_aerolinea_seq.nextval, 'Pegasus Airlines', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_AIRLINES', 'pegasus.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO aerolineas VALUES (id_aerolinea_seq.nextval, 'Ryanair', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_AIRLINES', 'ryanair.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO aerolineas VALUES (id_aerolinea_seq.nextval, 'Santa Barbara AirLines', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_AIRLINES', 'santa_barbara.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO aerolineas VALUES (id_aerolinea_seq.nextval, 'Sky Airline', EMPTY_BLOB()) RETURNING img INTO v_blob;
    v_bfile := BFILENAME('DIR_AIRLINES', 'sky.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
END;
/
/* TABLE insumos */
INSERT INTO insumos VALUES (id_insumo_seq.nextval, 'Agua destilada');
INSERT INTO insumos VALUES (id_insumo_seq.nextval, 'Agua oxigenada');
INSERT INTO insumos VALUES (id_insumo_seq.nextval, 'Alcohol');
INSERT INTO insumos VALUES (id_insumo_seq.nextval, 'Algodon');
INSERT INTO insumos VALUES (id_insumo_seq.nextval, 'Ampicilina');
INSERT INTO insumos VALUES (id_insumo_seq.nextval, 'Bisturi');
INSERT INTO insumos VALUES (id_insumo_seq.nextval, 'Cateter intravenoso');
INSERT INTO insumos VALUES (id_insumo_seq.nextval, 'Diclofenaco');
INSERT INTO insumos VALUES (id_insumo_seq.nextval, 'Esparadrapo');
INSERT INTO insumos VALUES (id_insumo_seq.nextval, 'Gasa');
INSERT INTO insumos VALUES (id_insumo_seq.nextval, 'Guantes desechables');
INSERT INTO insumos VALUES (id_insumo_seq.nextval, 'Hilo de sutura');
INSERT INTO insumos VALUES (id_insumo_seq.nextval, 'Jeringas');
INSERT INTO insumos VALUES (id_insumo_seq.nextval, 'Mascarilla');
INSERT INTO insumos VALUES (id_insumo_seq.nextval, 'Metronidazol');
INSERT INTO insumos VALUES (id_insumo_seq.nextval, 'Paracetamol');
INSERT INTO insumos VALUES (id_insumo_seq.nextval, 'Suero cloruro de sodio');
INSERT INTO insumos VALUES (id_insumo_seq.nextval, 'Suero Dextrosa');
INSERT INTO insumos VALUES (id_insumo_seq.nextval, 'Termometro');
INSERT INTO insumos VALUES (id_insumo_seq.nextval, 'Venda Elastica');
INSERT INTO insumos VALUES (id_insumo_seq.nextval, 'Yodo');
/
/* TABLE paises  
   Hay que hacerlo con un bloque anonimo para que se inserten las imagenes*/
DECLARE 
  v_blob BLOB;
  v_bfile BFILE;
BEGIN
    INSERT INTO paises VALUES (id_pais_seq.nextval, 'Alemania', EMPTY_BLOB()) RETURNING bandera INTO v_blob;
    v_bfile := BFILENAME('DIR_BANDERAS', 'de.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO paises VALUES (id_pais_seq.nextval, 'Argentina', EMPTY_BLOB()) RETURNING bandera INTO v_blob;
    v_bfile := BFILENAME('DIR_BANDERAS', 'ar.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO paises VALUES (id_pais_seq.nextval, 'Brasil', EMPTY_BLOB()) RETURNING bandera INTO v_blob;
    v_bfile := BFILENAME('DIR_BANDERAS', 'br.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO paises VALUES (id_pais_seq.nextval, 'China', EMPTY_BLOB()) RETURNING bandera INTO v_blob;
    v_bfile := BFILENAME('DIR_BANDERAS', 'cn.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO paises VALUES (id_pais_seq.nextval, 'España', EMPTY_BLOB()) RETURNING bandera INTO v_blob;
    v_bfile := BFILENAME('DIR_BANDERAS', 'es.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO paises VALUES (id_pais_seq.nextval, 'Estados Unidos', EMPTY_BLOB()) RETURNING bandera INTO v_blob;
    v_bfile := BFILENAME('DIR_BANDERAS', 'us.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO paises VALUES (id_pais_seq.nextval, 'Francia', EMPTY_BLOB()) RETURNING bandera INTO v_blob;
    v_bfile := BFILENAME('DIR_BANDERAS', 'fr.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO paises VALUES (id_pais_seq.nextval, 'Mexico', EMPTY_BLOB()) RETURNING bandera INTO v_blob;
    v_bfile := BFILENAME('DIR_BANDERAS', 'mx.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO paises VALUES (id_pais_seq.nextval, 'Reino Unido', EMPTY_BLOB()) RETURNING bandera INTO v_blob;
    v_bfile := BFILENAME('DIR_BANDERAS', 'gb.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO paises VALUES (id_pais_seq.nextval, 'Venezuela', EMPTY_BLOB()) RETURNING bandera INTO v_blob;
    v_bfile := BFILENAME('DIR_BANDERAS', 've.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO paises VALUES (id_pais_seq.nextval, 'Escocia',EMPTY_BLOB()) RETURNING bandera INTO v_blob;
    v_bfile := BFILENAME('DIR_BANDERAS', 'gb-sct.png');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
END;
/
/* TABLE estados */
INSERT INTO estados VALUES (id_estado_seq.nextval, 'Berlin', (SELECT id FROM paises WHERE nom = 'Alemania'), covid_data(3769000));
INSERT INTO estados VALUES (id_estado_seq.nextval, 'Hesse', (SELECT id FROM paises WHERE nom = 'Alemania'), covid_data(6866000));
INSERT INTO estados VALUES (id_estado_seq.nextval, 'Bremen', (SELECT id FROM paises WHERE nom = 'Alemania'), covid_data(547976));
INSERT INTO estados VALUES (id_estado_seq.nextval, 'Buenos Aires', (SELECT id FROM paises WHERE nom = 'Argentina'), covid_data(2890000));
INSERT INTO estados VALUES (id_estado_seq.nextval, 'Fortaleza', (SELECT id FROM paises WHERE nom = 'Brasil'), covid_data(2643000));
INSERT INTO estados VALUES (id_estado_seq.nextval, 'Hubei', (SELECT id FROM paises WHERE nom = 'China'), covid_data(58500000));
INSERT INTO estados VALUES (id_estado_seq.nextval, 'Sichuan', (SELECT id FROM paises WHERE nom = 'China'), covid_data(81100000));
INSERT INTO estados VALUES (id_estado_seq.nextval, 'Anhui', (SELECT id FROM paises WHERE nom = 'China'), covid_data(62000000));
INSERT INTO estados VALUES (id_estado_seq.nextval, 'Edimburgo', (SELECT id FROM paises WHERE nom = 'Escocia'), covid_data(6200500));
INSERT INTO estados VALUES (id_estado_seq.nextval, 'California', (SELECT id FROM paises WHERE nom = 'Estados Unidos'), covid_data(39510000));
INSERT INTO estados VALUES (id_estado_seq.nextval, 'Florida', (SELECT id FROM paises WHERE nom = 'Estados Unidos'), covid_data(21480000));
INSERT INTO estados VALUES (id_estado_seq.nextval, 'Louisiana', (SELECT id FROM paises WHERE nom = 'Estados Unidos'), covid_data(4649000));
INSERT INTO estados VALUES (id_estado_seq.nextval, 'Barcelona', (SELECT id FROM paises WHERE nom = 'España'), covid_data(5575000));
INSERT INTO estados VALUES (id_estado_seq.nextval, 'Granada', (SELECT id FROM paises WHERE nom = 'España'), covid_data(919700));
INSERT INTO estados VALUES (id_estado_seq.nextval, 'Zaragoza', (SELECT id FROM paises WHERE nom = 'España'), covid_data(968049));
INSERT INTO estados VALUES (id_estado_seq.nextval, 'Paris', (SELECT id FROM paises WHERE nom = 'Francia'), covid_data(968049));
INSERT INTO estados VALUES (id_estado_seq.nextval, 'Tamaulipas', (SELECT id FROM paises WHERE nom = 'Mexico'), covid_data(968049));
INSERT INTO estados VALUES (id_estado_seq.nextval, 'Londres', (SELECT id FROM paises WHERE nom = 'Reino Unido'), covid_data(968049));
INSERT INTO estados VALUES (id_estado_seq.nextval, 'Distrito Capital', (SELECT id FROM paises WHERE nom = 'Venezuela'), covid_data(1943901));
INSERT INTO estados VALUES (id_estado_seq.nextval, 'Lara', (SELECT id FROM paises WHERE nom = 'Venezuela'), covid_data(2019211));
INSERT INTO estados VALUES (id_estado_seq.nextval, 'Zulia', (SELECT id FROM paises WHERE nom = 'Venezuela'), covid_data(3704404));

/* TABLE ciudades */
INSERT INTO ciudades VALUES (id_ciudad_seq.nextval, 'Wiesbaden', (SELECT e.id FROM paises p JOIN estados e ON p.id = e.id_pais WHERE p.nom = 'Alemania' AND e.nom = 'Hesse'));
INSERT INTO ciudades VALUES (id_ciudad_seq.nextval, 'Kassel', (SELECT e.id FROM paises p JOIN estados e ON p.id = e.id_pais WHERE p.nom = 'Alemania' AND e.nom = 'Hesse'));
INSERT INTO ciudades VALUES (id_ciudad_seq.nextval, 'Berlin', (SELECT e.id FROM paises p JOIN estados e ON p.id = e.id_pais WHERE p.nom = 'Alemania' AND e.nom = 'Berlin'));
INSERT INTO ciudades VALUES (id_ciudad_seq.nextval, 'Bremerhaven', (SELECT e.id FROM paises p JOIN estados e ON p.id = e.id_pais WHERE p.nom = 'Alemania' AND e.nom = 'Bremen'));
INSERT INTO ciudades VALUES (id_ciudad_seq.nextval, 'Chengdu', (SELECT e.id FROM paises p JOIN estados e ON p.id = e.id_pais WHERE p.nom = 'China' AND e.nom = 'Sichuan'));
INSERT INTO ciudades VALUES (id_ciudad_seq.nextval, 'Wuhan', (SELECT e.id FROM paises p JOIN estados e ON p.id = e.id_pais WHERE p.nom = 'China' AND e.nom = 'Hubei'));
INSERT INTO ciudades VALUES (id_ciudad_seq.nextval, 'Xiangyang', (SELECT e.id FROM paises p JOIN estados e ON p.id = e.id_pais WHERE p.nom = 'China' AND e.nom = 'Hubei'));
INSERT INTO ciudades VALUES (id_ciudad_seq.nextval, 'Orlando', (SELECT e.id FROM paises p JOIN estados e ON p.id = e.id_pais WHERE p.nom = 'Estados Unidos' AND e.nom = 'Florida'));
INSERT INTO ciudades VALUES (id_ciudad_seq.nextval, 'Tampa', (SELECT e.id FROM paises p JOIN estados e ON p.id = e.id_pais WHERE p.nom = 'Estados Unidos' AND e.nom = 'Florida'));
INSERT INTO ciudades VALUES (id_ciudad_seq.nextval, 'New Orleans', (SELECT e.id FROM paises p JOIN estados e ON p.id = e.id_pais WHERE p.nom = 'Estados Unidos' AND e.nom = 'Louisiana'));
INSERT INTO ciudades VALUES (id_ciudad_seq.nextval, 'Sacramento', (SELECT e.id FROM paises p JOIN estados e ON p.id = e.id_pais WHERE p.nom = 'Estados Unidos' AND e.nom = 'California'));
INSERT INTO ciudades VALUES (id_ciudad_seq.nextval, 'Fresno', (SELECT e.id FROM paises p JOIN estados e ON p.id = e.id_pais WHERE p.nom = 'Estados Unidos' AND e.nom = 'California'));
INSERT INTO ciudades VALUES (id_ciudad_seq.nextval, 'Caracas', (SELECT e.id FROM paises p JOIN estados e ON p.id = e.id_pais WHERE p.nom = 'Venezuela' AND e.nom = 'Distrito Capital'));
INSERT INTO ciudades VALUES (id_ciudad_seq.nextval, 'Basquisimeto', (SELECT e.id FROM paises p JOIN estados e ON p.id = e.id_pais WHERE p.nom = 'Venezuela' AND e.nom = 'Lara'));
INSERT INTO ciudades VALUES (id_ciudad_seq.nextval, 'Maracaibo', (SELECT e.id FROM paises p JOIN estados e ON p.id = e.id_pais WHERE p.nom = 'Venezuela' AND e.nom = 'Zulia'));

/* TABLE urbanizaciones */
INSERT INTO urbanizaciones VALUES (id_urbanizacion_seq.nextval, 'Charlottenburg', (SELECT c.id FROM paises p JOIN estados e ON p.id = e.id_pais JOIN ciudades c ON e.id = c.id_estado WHERE p.nom = 'Alemania' AND e.nom = 'Berlin' AND c.nom = 'Berlin'));
INSERT INTO urbanizaciones VALUES (id_urbanizacion_seq.nextval, 'Kreuzberg', (SELECT c.id FROM paises p JOIN estados e ON p.id = e.id_pais JOIN ciudades c ON e.id = c.id_estado WHERE p.nom = 'Alemania' AND e.nom = 'Berlin' AND c.nom = 'Berlin'));
INSERT INTO urbanizaciones VALUES (id_urbanizacion_seq.nextval, 'Tegel', (SELECT c.id FROM paises p JOIN estados e ON p.id = e.id_pais JOIN ciudades c ON e.id = c.id_estado WHERE p.nom = 'Alemania' AND e.nom = 'Berlin' AND c.nom = 'Berlin'));
INSERT INTO urbanizaciones VALUES (id_urbanizacion_seq.nextval, 'Parkway', (SELECT c.id FROM paises p JOIN estados e ON p.id = e.id_pais JOIN ciudades c ON e.id = c.id_estado WHERE p.nom = 'Estados Unidos' AND e.nom = 'California' AND c.nom = 'Fresno'));
INSERT INTO urbanizaciones VALUES (id_urbanizacion_seq.nextval, 'Lakeview', (SELECT c.id FROM paises p JOIN estados e ON p.id = e.id_pais JOIN ciudades c ON e.id = c.id_estado WHERE p.nom = 'Estados Unidos' AND e.nom = 'Louisiana' AND c.nom = 'New Orleans'));
INSERT INTO urbanizaciones VALUES (id_urbanizacion_seq.nextval, 'Tulane', (SELECT c.id FROM paises p JOIN estados e ON p.id = e.id_pais JOIN ciudades c ON e.id = c.id_estado WHERE p.nom = 'Estados Unidos' AND e.nom = 'Louisiana' AND c.nom = 'New Orleans'));
INSERT INTO urbanizaciones VALUES (id_urbanizacion_seq.nextval, 'Chunxi Road', (SELECT c.id FROM paises p JOIN estados e ON p.id = e.id_pais JOIN ciudades c ON e.id = c.id_estado WHERE p.nom = 'China' AND e.nom = 'Sichuan' AND c.nom = 'Chengdu'));
INSERT INTO urbanizaciones VALUES (id_urbanizacion_seq.nextval, 'Jianghan Road', (SELECT c.id FROM paises p JOIN estados e ON p.id = e.id_pais JOIN ciudades c ON e.id = c.id_estado WHERE p.nom = 'China' AND e.nom = 'Hubei' AND c.nom = 'Wuhan'));
INSERT INTO urbanizaciones VALUES (id_urbanizacion_seq.nextval, 'Zhongnan', (SELECT c.id FROM paises p JOIN estados e ON p.id = e.id_pais JOIN ciudades c ON e.id = c.id_estado WHERE p.nom = 'China' AND e.nom = 'Hubei' AND c.nom = 'Wuhan'));
INSERT INTO urbanizaciones VALUES (id_urbanizacion_seq.nextval, 'Wuhouci', (SELECT c.id FROM paises p JOIN estados e ON p.id = e.id_pais JOIN ciudades c ON e.id = c.id_estado WHERE p.nom = 'China' AND e.nom = 'Sichuan' AND c.nom = 'Chengdu'));
INSERT INTO urbanizaciones VALUES (id_urbanizacion_seq.nextval, 'La Castellana', (SELECT c.id FROM paises p JOIN estados e ON p.id = e.id_pais JOIN ciudades c ON e.id = c.id_estado WHERE p.nom = 'Venezuela' AND e.nom = 'Distrito Capital' AND c.nom = 'Caracas'));
INSERT INTO urbanizaciones VALUES (id_urbanizacion_seq.nextval, 'Colinas de Bello Monte', (SELECT c.id FROM paises p JOIN estados e ON p.id = e.id_pais JOIN ciudades c ON e.id = c.id_estado WHERE p.nom = 'Venezuela' AND e.nom = 'Distrito Capital' AND c.nom = 'Caracas'));
INSERT INTO urbanizaciones VALUES (id_urbanizacion_seq.nextval, 'Montalban', (SELECT c.id FROM paises p JOIN estados e ON p.id = e.id_pais JOIN ciudades c ON e.id = c.id_estado WHERE p.nom = 'Venezuela' AND e.nom = 'Distrito Capital' AND c.nom = 'Caracas'));
INSERT INTO urbanizaciones VALUES (id_urbanizacion_seq.nextval, 'Ziruma', (SELECT c.id FROM paises p JOIN estados e ON p.id = e.id_pais JOIN ciudades c ON e.id = c.id_estado WHERE p.nom = 'Venezuela' AND e.nom = 'Zulia' AND c.nom = 'Maracaibo'));
INSERT INTO urbanizaciones VALUES (id_urbanizacion_seq.nextval, 'Las Delicias', (SELECT c.id FROM paises p JOIN estados e ON p.id = e.id_pais JOIN ciudades c ON e.id = c.id_estado WHERE p.nom = 'Venezuela' AND e.nom = 'Zulia' AND c.nom = 'Maracaibo'));

/* TABLE calles */
INSERT INTO CALLES VALUES (id_calle_seq.nextval, 'S. Rendon', 70119, (SELECT u.id FROM URBANIZACIONES u JOIN ciudades c ON c.id = u.id_ciudad JOIN estados e ON e.id = c.id_estado JOIN paises p ON p.id = e.id_pais WHERE u.nom = 'Tulane' AND c.nom = 'New Orleans' AND e.nom = 'Louisiana' AND p.nom = 'Estados Unidos'));
INSERT INTO CALLES VALUES (id_calle_seq.nextval, 'S. Clark', 72626, (SELECT u.id FROM URBANIZACIONES u JOIN ciudades c ON c.id = u.id_ciudad JOIN estados e ON e.id = c.id_estado JOIN paises p ON p.id = e.id_pais WHERE u.nom = 'Tulane' AND c.nom = 'New Orleans' AND e.nom = 'Louisiana' AND p.nom = 'Estados Unidos'));
INSERT INTO CALLES VALUES (id_calle_seq.nextval, 'Perdido', 53158, (SELECT u.id FROM URBANIZACIONES u JOIN ciudades c ON c.id = u.id_ciudad JOIN estados e ON e.id = c.id_estado JOIN paises p ON p.id = e.id_pais WHERE u.nom = 'Tulane' AND c.nom = 'New Orleans' AND e.nom = 'Louisiana' AND p.nom = 'Estados Unidos'));
INSERT INTO CALLES VALUES (id_calle_seq.nextval, 'Baudin', 54510, (SELECT u.id FROM URBANIZACIONES u JOIN ciudades c ON c.id = u.id_ciudad JOIN estados e ON e.id = c.id_estado JOIN paises p ON p.id = e.id_pais WHERE u.nom = 'Tulane' AND c.nom = 'New Orleans' AND e.nom = 'Louisiana' AND p.nom = 'Estados Unidos'));
INSERT INTO CALLES VALUES (id_calle_seq.nextval, 'S. Lopez', 72626, (SELECT u.id FROM URBANIZACIONES u JOIN ciudades c ON c.id = u.id_ciudad JOIN estados e ON e.id = c.id_estado JOIN paises p ON p.id = e.id_pais WHERE u.nom = 'Tulane' AND c.nom = 'New Orleans' AND e.nom = 'Louisiana' AND p.nom = 'Estados Unidos'));
INSERT INTO CALLES VALUES (id_calle_seq.nextval, 'S. Salcedo', 75026, (SELECT u.id FROM URBANIZACIONES u JOIN ciudades c ON c.id = u.id_ciudad JOIN estados e ON e.id = c.id_estado JOIN paises p ON p.id = e.id_pais WHERE u.nom = 'Tulane' AND c.nom = 'New Orleans' AND e.nom = 'Louisiana' AND p.nom = 'Estados Unidos'));
INSERT INTO CALLES VALUES (id_calle_seq.nextval, 'S. Genois', 51015, (SELECT u.id FROM URBANIZACIONES u JOIN ciudades c ON c.id = u.id_ciudad JOIN estados e ON e.id = c.id_estado JOIN paises p ON p.id = e.id_pais WHERE u.nom = 'Tulane' AND c.nom = 'New Orleans' AND e.nom = 'Louisiana' AND p.nom = 'Estados Unidos'));
INSERT INTO CALLES VALUES (id_calle_seq.nextval, 'D Hemecourt', 21555, (SELECT u.id FROM URBANIZACIONES u JOIN ciudades c ON c.id = u.id_ciudad JOIN estados e ON e.id = c.id_estado JOIN paises p ON p.id = e.id_pais WHERE u.nom = 'Tulane' AND c.nom = 'New Orleans' AND e.nom = 'Louisiana' AND p.nom = 'Estados Unidos'));
INSERT INTO CALLES VALUES (id_calle_seq.nextval, 'Gravier', 54106, (SELECT u.id FROM URBANIZACIONES u JOIN ciudades c ON c.id = u.id_ciudad JOIN estados e ON e.id = c.id_estado JOIN paises p ON p.id = e.id_pais WHERE u.nom = 'Tulane' AND c.nom = 'New Orleans' AND e.nom = 'Louisiana' AND p.nom = 'Estados Unidos'));
INSERT INTO CALLES VALUES (id_calle_seq.nextval, 'S. Telemachus', 72005, (SELECT u.id FROM URBANIZACIONES u JOIN ciudades c ON c.id = u.id_ciudad JOIN estados e ON e.id = c.id_estado JOIN paises p ON p.id = e.id_pais WHERE u.nom = 'Tulane' AND c.nom = 'New Orleans' AND e.nom = 'Louisiana' AND p.nom = 'Estados Unidos'));
INSERT INTO CALLES VALUES (id_calle_seq.nextval, 'Grant Avenue', 15483, (SELECT u.id FROM URBANIZACIONES u JOIN ciudades c ON c.id = u.id_ciudad JOIN estados e ON e.id = c.id_estado JOIN paises p ON p.id = e.id_pais WHERE u.nom = 'Parkway' AND c.nom = 'Fresno' AND e.nom = 'California' AND p.nom = 'Estados Unidos'));
INSERT INTO CALLES VALUES (id_calle_seq.nextval, 'Maiden Lane', 12545, (SELECT u.id FROM URBANIZACIONES u JOIN ciudades c ON c.id = u.id_ciudad JOIN estados e ON e.id = c.id_estado JOIN paises p ON p.id = e.id_pais WHERE u.nom = 'Parkway' AND c.nom = 'Fresno' AND e.nom = 'California' AND p.nom = 'Estados Unidos'));
INSERT INTO CALLES VALUES (id_calle_seq.nextval, 'State Street', 86527, (SELECT u.id FROM URBANIZACIONES u JOIN ciudades c ON c.id = u.id_ciudad JOIN estados e ON e.id = c.id_estado JOIN paises p ON p.id = e.id_pais WHERE u.nom = 'Parkway' AND c.nom = 'Fresno' AND e.nom = 'California' AND p.nom = 'Estados Unidos'));
INSERT INTO CALLES VALUES (id_calle_seq.nextval, 'S. Rick', 68548, (SELECT u.id FROM URBANIZACIONES u JOIN ciudades c ON c.id = u.id_ciudad JOIN estados e ON e.id = c.id_estado JOIN paises p ON p.id = e.id_pais WHERE u.nom = 'Charlottenburg' AND c.nom = 'Berlin' AND e.nom = 'Berlin' AND p.nom = 'Alemania'));
INSERT INTO CALLES VALUES (id_calle_seq.nextval, 'M. Smith', 11547, (SELECT u.id FROM URBANIZACIONES u JOIN ciudades c ON c.id = u.id_ciudad JOIN estados e ON e.id = c.id_estado JOIN paises p ON p.id = e.id_pais WHERE u.nom = 'Kreuzberg' AND c.nom = 'Berlin' AND e.nom = 'Berlin' AND p.nom = 'Alemania'));
/
/* TABLE personas
    Hay que hacerlo con un bloque anonimo para que se inserten las imagenes*/
DECLARE 
  v_blob BLOB;
  v_bfile BFILE;
BEGIN
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Frank', null, 'Hesse', 'R', '01/08/1999', null, 'M'),1) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person01.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Leo', null, 'Barnes', 'H', '10/05/1996', null, 'M'),1) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person04.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Carmina', null, 'Zucceada', 'A', '07/05/1998', null, 'F'),2) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person02.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Josh', null, 'Hamilton', 'G', '24/11/1988', null, 'M'),3) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person06.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Faryd', null, 'Morningstar', 'D', '17/04/1968', null, 'M'),1) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person07.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Kim', null, 'Parker', 'W', '17/11/1998', null, 'F'),5) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person05.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Ruby', null, 'Mikan', 'F', '14/08/1992', null, 'F'), 7) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person02.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Vladimir', null, 'Makarov', 'F', '04/10/1993', null, 'M'), 9) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person10.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Dmitri', null, 'Smirnov', 'A', '14/07/1998', null, 'M'), 10) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person20.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Alex', null, 'Preobrazhensky', 'V', '17/04/1996', null, 'M'), 10) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person12.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Anna', null, 'Preobrazhensky', 'V', '27/09/1996', null, 'F'), 5) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person08.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Ivan', null, 'Kuznetsov', 'D', '17/04/1996', null, 'M'), 4) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person09.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'John', null, 'Ki', 'D', '16/10/1997', null, 'M'), 2) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person26.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Emily', null, 'Rose', 'C', '07/11/1999', null, 'F'), 8) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person11.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Gregg', null, 'Spinetti', 'J', '01/11/1997', null, 'M'), 9) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person23.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Niels', null, 'Petersen', 'J', '08/11/1987', null, 'M'), 5) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person13.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Shia', null, 'Morgan', 'J', '08/11/1997', null, 'F'), 7) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person15.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Shelby', null, 'Morgan', 'J', '01/12/1998', null, 'F'), 2) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person19.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Alice', null, 'Nightray', 'F', '08/07/1995', null, 'F'), 5) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person30.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Piero', null, 'Vilchez', 'A', '05/07/1998', null, 'M'), 6) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person14.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Omar', null, 'Hernandez', 'Barrera', '07/07/1978', null, 'M'), 6) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person16.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Stefano', null, 'Hernandez', 'Q', '01/05/1978', null, 'M'), 6) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person18.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Jaz', null, 'Radke', 'Q', '01/12/1998', null, 'F'), 8) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person29.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Henry', null, 'Modrig', 'Rodriguez', '07/11/1989', null, 'M'), 1) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person17.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Kylie', null, 'Hann', 'S', '13/09/1991', null, 'F'), 3) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person25.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Gavin', null, 'Cringe', 'Preach', '09/11/1988', null, 'M'), 4) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person27.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Alberto', 'Arturo', 'Gavin', 'Colmenares', '12/12/1986', null, 'M'), 4) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person21.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Dia', null, 'Hansen', null, '12/03/1996', null, 'F'), 8) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person28.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Kingsley', null, 'Coman', 'Jr', '08/07/1998', null, 'M'), 9) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person24.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Cassie', null, 'Kench', 'A', '01/09/1999', null, 'F'), 10) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person38.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
    INSERT INTO PERSONAS p VALUES (id_persona_seq.nextval, persona(EMPTY_BLOB(), 'Ethan', null, 'Hartmann', 'A', '05/10/1997', '19/06/2020', 'M'), 10) RETURNING p.pers.img INTO v_blob;
    v_bfile := BFILENAME('DIR_PEOPLE', 'person32.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, SYS.DBMS_LOB.GETLENGTH(v_bfile));
    DBMS_LOB.CLOSE(v_bfile);
END;
/
/* TABLE recintos_salud */
INSERT INTO recintos_salud VALUES (id_recinto_salud_seq.nextval,'Hospital Medical Center','Pub', 500, covid_data(356),1);
INSERT INTO recintos_salud VALUES (id_recinto_salud_seq.nextval,'Health University Hospital','Priv', 200, covid_data(110),2);
INSERT INTO recintos_salud VALUES (id_recinto_salud_seq.nextval,'Childens and Women Hospital','Pub', 150, covid_data(65),3);
INSERT INTO recintos_salud VALUES (id_recinto_salud_seq.nextval,'Hospital Johns Hopkins','Pub', 750, covid_data(652),4);
INSERT INTO recintos_salud VALUES (id_recinto_salud_seq.nextval,'Jackson Memorial Hospital','Pub', 300, covid_data(156),5);
INSERT INTO recintos_salud VALUES (id_recinto_salud_seq.nextval,'Hospital General New Orleans','Pub', 1500, covid_data(1264),6);
INSERT INTO recintos_salud VALUES (id_recinto_salud_seq.nextval,'Pediatric Rheumatology Program','Priv', 210, covid_data(127),7);
INSERT INTO recintos_salud VALUES (id_recinto_salud_seq.nextval,'Robert Wood Johnson Universty Hospital','Pub', 790, covid_data(569),8);
INSERT INTO recintos_salud VALUES (id_recinto_salud_seq.nextval,'Hospital for Special surgery main hospital','Priv', 530, covid_data(147),9);
INSERT INTO recintos_salud VALUES (id_recinto_salud_seq.nextval,'Nicklaus Childens Hospital','Pub', 650, covid_data(458),10);
INSERT INTO recintos_salud VALUES (id_recinto_salud_seq.nextval,'Beth Israel Hospital','Pub', 180, covid_data(141),11);
INSERT INTO recintos_salud VALUES (id_recinto_salud_seq.nextval,'Hospital Monte Sinai','Priv', 690, covid_data(154),12);
INSERT INTO recintos_salud VALUES (id_recinto_salud_seq.nextval,'Stanford Medicine','Priv', 910, covid_data(569),13);
INSERT INTO recintos_salud VALUES (id_recinto_salud_seq.nextval,'Virginia Mason Hospital','Pub', 610, covid_data(298),14);
INSERT INTO recintos_salud VALUES (id_recinto_salud_seq.nextval,'Hospital General Fresno','Pub', 1250, covid_data(945),15);

/* TABLE historico_cierre_fronteras */
INSERT INTO historico_cierre_fronteras VALUES (id_hist_cierre_seq.nextval,historia('15/03/2020','13/05/2020'),1);
INSERT INTO historico_cierre_fronteras VALUES (id_hist_cierre_seq.nextval,historia('25/03/2020','30/05/2020'),2);
INSERT INTO historico_cierre_fronteras VALUES (id_hist_cierre_seq.nextval,historia('13/03/2020','13/04/2020'),3);
INSERT INTO historico_cierre_fronteras VALUES (id_hist_cierre_seq.nextval,historia('05/04/2020',null),4);
INSERT INTO historico_cierre_fronteras VALUES (id_hist_cierre_seq.nextval,historia('15/03/2020','15/04/2020'),5);
INSERT INTO historico_cierre_fronteras VALUES (id_hist_cierre_seq.nextval,historia('21/04/2020','21/05/2020'),5);
INSERT INTO historico_cierre_fronteras VALUES (id_hist_cierre_seq.nextval,historia('01/06/2020',null),5);
INSERT INTO historico_cierre_fronteras VALUES (id_hist_cierre_seq.nextval,historia('13/03/2020','07/05/2020'),6);
INSERT INTO historico_cierre_fronteras VALUES (id_hist_cierre_seq.nextval,historia('25/05/2020','25/06/2020'),6);
INSERT INTO historico_cierre_fronteras VALUES (id_hist_cierre_seq.nextval,historia('07/04/2020','07/05/2020'),7);
INSERT INTO historico_cierre_fronteras VALUES (id_hist_cierre_seq.nextval,historia('25/03/2020',NULL),8);
INSERT INTO historico_cierre_fronteras VALUES (id_hist_cierre_seq.nextval,historia('10/04/2020','25/05/2020'),9);
INSERT INTO historico_cierre_fronteras VALUES (id_hist_cierre_seq.nextval,historia('15/03/2020','15/04/2020'),10);
INSERT INTO historico_cierre_fronteras VALUES (id_hist_cierre_seq.nextval,historia('21/04/2020','21/05/2020'),10);
INSERT INTO historico_cierre_fronteras VALUES (id_hist_cierre_seq.nextval,historia('01/06/2020',null),10);

/* TABLE modelos */
INSERT INTO modelos VALUES (1,'Libre Movilidad');
INSERT INTO modelos VALUES (2,'Cuarentena');
INSERT INTO modelos VALUES (3,'Movilidad Reducida 1-4');
INSERT INTO modelos VALUES (4,'Movilidad Reducida 1-8');

/* TABLE historico_modelos */
INSERT INTO historico_modelos VALUES (id_hist_modelo_seq.nextval,historia('01/03/2020',null),1,1); 
INSERT INTO historico_modelos VALUES (id_hist_modelo_seq.nextval,historia('28/05/2020',null),2,2); 
INSERT INTO historico_modelos VALUES (id_hist_modelo_seq.nextval,historia('01/06/2020',null),3,3); 
INSERT INTO historico_modelos VALUES (id_hist_modelo_seq.nextval,historia('14/02/2020',null),4,1); 
INSERT INTO historico_modelos VALUES (id_hist_modelo_seq.nextval,historia('21/06/2020',null),5,2); 
INSERT INTO historico_modelos VALUES (id_hist_modelo_seq.nextval,historia('11/07/2020',null),6,1); 
INSERT INTO historico_modelos VALUES (id_hist_modelo_seq.nextval,historia('09/06/2020',null),7,1); 
INSERT INTO historico_modelos VALUES (id_hist_modelo_seq.nextval,historia('29/03/2020',null),8,1); 
INSERT INTO historico_modelos VALUES (id_hist_modelo_seq.nextval,historia('12/04/2020','01/06/2020'),9,1); 
INSERT INTO historico_modelos VALUES (id_hist_modelo_seq.nextval,historia('01/06/2020',null),9,2); 
INSERT INTO historico_modelos VALUES (id_hist_modelo_seq.nextval,historia('05/04/2020',null),11,1); 
INSERT INTO historico_modelos VALUES (id_hist_modelo_seq.nextval,historia('08/05/2020',null),12,2); 
INSERT INTO historico_modelos VALUES (id_hist_modelo_seq.nextval,historia('12/04/2020',null),13,4); 
INSERT INTO historico_modelos VALUES (id_hist_modelo_seq.nextval,historia('15/03/2020',null),14,1); 
INSERT INTO historico_modelos VALUES (id_hist_modelo_seq.nextval,historia('27/03/2020',null),15,4); 

/* TABLE historico_ayuda_humanitaria */
INSERT INTO historico_ayuda_humanitaria VALUES (id_hist_ayuda_seq.nextval,historia('28/02/2020',null),100000,1,10);
INSERT INTO historico_ayuda_humanitaria VALUES (id_hist_ayuda_seq.nextval,historia('27/03/2020',null),50000,1,10);
INSERT INTO historico_ayuda_humanitaria VALUES (id_hist_ayuda_seq.nextval,historia('21/04/2020',null),120000,1,10);
INSERT INTO historico_ayuda_humanitaria VALUES (id_hist_ayuda_seq.nextval,historia('06/03/2020',null),300000,1,10);
INSERT INTO historico_ayuda_humanitaria VALUES (id_hist_ayuda_seq.nextval,historia('19/05/2020',null),1000000,1,10);
INSERT INTO historico_ayuda_humanitaria VALUES (id_hist_ayuda_seq.nextval,historia('27/06/2020',null),1200000,1,10);
INSERT INTO historico_ayuda_humanitaria VALUES (id_hist_ayuda_seq.nextval,historia('14/05/2020',null),50000,1,10);
INSERT INTO historico_ayuda_humanitaria VALUES (id_hist_ayuda_seq.nextval,historia('27/04/2020',null),650000,1,10);
INSERT INTO historico_ayuda_humanitaria VALUES (id_hist_ayuda_seq.nextval,historia('04/06/2020',null),125000,1,10);
INSERT INTO historico_ayuda_humanitaria VALUES (id_hist_ayuda_seq.nextval,historia('15/03/2020',null),25000,1,10);
INSERT INTO historico_ayuda_humanitaria VALUES (id_hist_ayuda_seq.nextval,historia('27/04/2020',null),10000,1,10);
INSERT INTO historico_ayuda_humanitaria VALUES (id_hist_ayuda_seq.nextval,historia('07/03/2020',null),800000,1,10);
INSERT INTO historico_ayuda_humanitaria VALUES (id_hist_ayuda_seq.nextval,historia('09/04/2020',null),1000000,1,10);
INSERT INTO historico_ayuda_humanitaria VALUES (id_hist_ayuda_seq.nextval,historia('17/03/2020',null),750000,1,10);
INSERT INTO historico_ayuda_humanitaria VALUES (id_hist_ayuda_seq.nextval,historia('24/04/2020',null),70000,1,10);

/* TABLE historico_viajes */
INSERT INTO historico_viajes VALUES (id_hist_viajes_seq.nextval,historia('23/04/2020','23/04/2020'),953842,1,6,5);
INSERT INTO historico_viajes VALUES (id_hist_viajes_seq.nextval,historia('15/06/2020','15/06/2020'),598426,1,11,2);
INSERT INTO historico_viajes VALUES (id_hist_viajes_seq.nextval,historia('28/02/2020','01/03/2020'),984265,3,1,5);
INSERT INTO historico_viajes VALUES (id_hist_viajes_seq.nextval,historia('23/05/2020','23/05/2020'),584637,3,6,14);
INSERT INTO historico_viajes VALUES (id_hist_viajes_seq.nextval,historia('07/02/2020','07/02/2020'),125487,2,3,5);
INSERT INTO historico_viajes VALUES (id_hist_viajes_seq.nextval,historia('07/03/2020','08/03/2020'),965447,2,7,15);
INSERT INTO historico_viajes VALUES (id_hist_viajes_seq.nextval,historia('14/01/2020','14/01/2020'),487556,5,10,6);
INSERT INTO historico_viajes VALUES (id_hist_viajes_seq.nextval,historia('11/05/2020','11/05/2020'),695844,6,7,12);
INSERT INTO historico_viajes VALUES (id_hist_viajes_seq.nextval,historia('09/04/2020','09/04/2020'),112254,8,8,3);
INSERT INTO historico_viajes VALUES (id_hist_viajes_seq.nextval,historia('13/04/2020','13/04/2020'),458962,9,12,8);
INSERT INTO historico_viajes VALUES (id_hist_viajes_seq.nextval,historia('28/04/2020','28/04/2020'),156687,10,7,8);
INSERT INTO historico_viajes VALUES (id_hist_viajes_seq.nextval,historia('27/05/2020','27/05/2020'),336584,12,4,7);
INSERT INTO historico_viajes VALUES (id_hist_viajes_seq.nextval,historia('15/04/2020','15/04/2020'),944526,12,12,4);
INSERT INTO historico_viajes VALUES (id_hist_viajes_seq.nextval,historia('20/02/2020','20/02/2020'),452147,14,15,1);
INSERT INTO historico_viajes VALUES (id_hist_viajes_seq.nextval,historia('01/03/2020','01/03/2020'),568465,5,1,5);

/* TABLE historico_tratamiento */
INSERT INTO historico_tratamiento VALUES (id_hist_tratamiento_seq.nextval,historia('12/03/2020','21/04/2020'),1,1);
INSERT INTO historico_tratamiento VALUES (id_hist_tratamiento_seq.nextval,historia('30/04/2020','25/05/2020'),2,1);
INSERT INTO historico_tratamiento VALUES (id_hist_tratamiento_seq.nextval,historia('04/06/2020','10/07/2020'),4,3);
INSERT INTO historico_tratamiento VALUES (id_hist_tratamiento_seq.nextval,historia('16/05/2020',null),7,3);
INSERT INTO historico_tratamiento VALUES (id_hist_tratamiento_seq.nextval,historia('28/03/2020',null),9,5);
INSERT INTO historico_tratamiento VALUES (id_hist_tratamiento_seq.nextval,historia('15/02/2020','11/04/2020'),11,5);
INSERT INTO historico_tratamiento VALUES (id_hist_tratamiento_seq.nextval,historia('07/04/2020','10/05/2020'),13,6);
INSERT INTO historico_tratamiento VALUES (id_hist_tratamiento_seq.nextval,historia('09/04/2020',null),14,7);
INSERT INTO historico_tratamiento VALUES (id_hist_tratamiento_seq.nextval,historia('19/06/2020','01/07/2020'),16,7);
INSERT INTO historico_tratamiento VALUES (id_hist_tratamiento_seq.nextval,historia('05/05/2020','20/06/2020'),17,7);
INSERT INTO historico_tratamiento VALUES (id_hist_tratamiento_seq.nextval,historia('07/06/2020',null),19,10);
INSERT INTO historico_tratamiento VALUES (id_hist_tratamiento_seq.nextval,historia('17/04/2020','28/05/2020'),20,10);
INSERT INTO historico_tratamiento VALUES (id_hist_tratamiento_seq.nextval,historia('28/03/2020',null),24,9);
INSERT INTO historico_tratamiento VALUES (id_hist_tratamiento_seq.nextval,historia('24/02/2020','01/04/2020'),27,9);
INSERT INTO historico_tratamiento VALUES (id_hist_tratamiento_seq.nextval,historia('20/04/2020',null),26,8);

/* TABLE A_I */
INSERT INTO A_I VALUES (120,1,1);
INSERT INTO A_I VALUES (100,2,1);
INSERT INTO A_I VALUES (210,3,1);
INSERT INTO A_I VALUES (150,4,1);
INSERT INTO A_I VALUES (250,1,2);
INSERT INTO A_I VALUES (100,2,2);
INSERT INTO A_I VALUES (350,5,2);
INSERT INTO A_I VALUES (90,6,2);
INSERT INTO A_I VALUES (80,7,3);
INSERT INTO A_I VALUES (250,10,3);
INSERT INTO A_I VALUES (190,11,4);
INSERT INTO A_I VALUES (300,12,4);
INSERT INTO A_I VALUES (410,10,4);
INSERT INTO A_I VALUES (140,7,7);
INSERT INTO A_I VALUES (210,8,7);

/* TABLE H_I */
INSERT INTO H_I VALUES (120,1,11);
INSERT INTO H_I VALUES (100,2,11);
INSERT INTO H_I VALUES (210,3,11);
INSERT INTO H_I VALUES (150,4,11);
INSERT INTO H_I VALUES (250,1,2);
INSERT INTO H_I VALUES (100,2,2);
INSERT INTO H_I VALUES (350,5,2);
INSERT INTO H_I VALUES (90,6,2);
INSERT INTO H_I VALUES (80,7,3);
INSERT INTO H_I VALUES (250,10,3);
INSERT INTO H_I VALUES (190,11,5);
INSERT INTO H_I VALUES (300,12,5);
INSERT INTO H_I VALUES (410,10,5);
INSERT INTO H_I VALUES (140,7,8);
INSERT INTO H_I VALUES (210,8,8);

/* TABLE E_P */
INSERT INTO E_P VALUES (1,1);
INSERT INTO E_P VALUES (2,1);
INSERT INTO E_P VALUES (3,2);
INSERT INTO E_P VALUES (4,2);
INSERT INTO E_P VALUES (5,3);
INSERT INTO E_P VALUES (6,3);
INSERT INTO E_P VALUES (7,6);
INSERT INTO E_P VALUES (8,11);
INSERT INTO E_P VALUES (9,10);
INSERT INTO E_P VALUES (10,10);
INSERT INTO E_P VALUES (11,15);
INSERT INTO E_P VALUES (12,15);
INSERT INTO E_P VALUES (13,7);
INSERT INTO E_P VALUES (14,7);
INSERT INTO E_P VALUES (15,8);

/* TABLE C_HV */
INSERT INTO C_VP VALUES (1,4);
INSERT INTO C_VP VALUES (1,11);
INSERT INTO C_VP VALUES (3,4);
INSERT INTO C_VP VALUES (3,10);
INSERT INTO C_VP VALUES (5,14);
INSERT INTO C_VP VALUES (6,5);
INSERT INTO C_VP VALUES (7,14);
INSERT INTO C_VP VALUES (7,8);
INSERT INTO C_VP VALUES (10,14);
INSERT INTO C_VP VALUES (10,12);
INSERT INTO C_VP VALUES (11,11);
INSERT INTO C_VP VALUES (11,5);
INSERT INTO C_VP VALUES (8,2);
INSERT INTO C_VP VALUES (2,9);
INSERT INTO C_VP VALUES (13,15);


/* TABLE P_HV */
INSERT INTO P_HV VALUES (1,6);
INSERT INTO P_HV VALUES (1,8);
INSERT INTO P_HV VALUES (3,3);
INSERT INTO P_HV VALUES (3,2);
INSERT INTO P_HV VALUES (5,9);
INSERT INTO P_HV VALUES (6,3);
INSERT INTO P_HV VALUES (7,15);
INSERT INTO P_HV VALUES (7,13);
INSERT INTO P_HV VALUES (10,10);
INSERT INTO P_HV VALUES (10,4);
INSERT INTO P_HV VALUES (11,13);
INSERT INTO P_HV VALUES (11,3);
INSERT INTO P_HV VALUES (8,1);
INSERT INTO P_HV VALUES (2,2);
INSERT INTO P_HV VALUES (13,12);

/* TABLE P_PAT */
INSERT INTO P_PAT VALUES (7,10);
INSERT INTO P_PAT VALUES (4,13);
INSERT INTO P_PAT VALUES (7,9);
INSERT INTO P_PAT VALUES (3,13);
INSERT INTO P_PAT VALUES (6,12);
INSERT INTO P_PAT VALUES (2,8);
INSERT INTO P_PAT VALUES (10,9);
INSERT INTO P_PAT VALUES (15,11);
INSERT INTO P_PAT VALUES (10,14);
INSERT INTO P_PAT VALUES (1,10);
INSERT INTO P_PAT VALUES (8,4);
INSERT INTO P_PAT VALUES (15,13);
INSERT INTO P_PAT VALUES (11,12);
INSERT INTO P_PAT VALUES (8,6);
INSERT INTO P_PAT VALUES (1,8);

/* TABLE P_S */
INSERT INTO P_S VALUES (11,9);
INSERT INTO P_S VALUES (4,1);
INSERT INTO P_S VALUES (2,12);
INSERT INTO P_S VALUES (4,7);
INSERT INTO P_S VALUES (12,6);
INSERT INTO P_S VALUES (15,2);
INSERT INTO P_S VALUES (6,9);
INSERT INTO P_S VALUES (15,14);
INSERT INTO P_S VALUES (6,15);
INSERT INTO P_S VALUES (10,13);
INSERT INTO P_S VALUES (1,11);
INSERT INTO P_S VALUES (9,13);
INSERT INTO P_S VALUES (5,10);
INSERT INTO P_S VALUES (9,14);
INSERT INTO P_S VALUES (8,14);

/* TABLE P_PROV */
INSERT INTO P_PROV VALUES (1,8,15.24,5.12,0);
INSERT INTO P_PROV VALUES (2,9,25.12,15.98,0);
INSERT INTO P_PROV VALUES (3,7,75.24,50.65,1);
INSERT INTO P_PROV VALUES (4,5,52.36,30.45,1);
INSERT INTO P_PROV VALUES (5,8,120.15,60.25,1);
INSERT INTO P_PROV VALUES (6,15,80.25,50.36,0);
INSERT INTO P_PROV VALUES (7,7,24.21,14.25,1);
INSERT INTO P_PROV VALUES (8,4,45.65,20.36,2);
INSERT INTO P_PROV VALUES (9,12,54.26,26.45,0);
INSERT INTO P_PROV VALUES (12,9,33.71,10.89,1);
INSERT INTO P_PROV VALUES (13,2,76.94,41.09,0);
INSERT INTO P_PROV VALUES (14,5,80.19,45.32,1);
INSERT INTO P_PROV VALUES (15,9,20.64,9.91,0);
INSERT INTO P_PROV VALUES (16,3,0.11,0.1,4);
INSERT INTO P_PROV VALUES (17,8,60.39,30.11,1);
INSERT INTO P_PROV VALUES (18,11,50.10,25.60,3);

/* TABLE infectados_covid */
INSERT INTO INFECTADOS_COVID VALUES (id_infectado_seq.nextval,historia('12/03/2020','21/04/2020'),'I',1,1,5);
INSERT INTO INFECTADOS_COVID VALUES (id_infectado_seq.nextval,historia('30/04/2020','25/05/2020'),'I',2,2,11);
INSERT INTO INFECTADOS_COVID VALUES (id_infectado_seq.nextval,historia('04/06/2020','10/07/2020'),'M',4,3,5);
INSERT INTO INFECTADOS_COVID VALUES (id_infectado_seq.nextval,historia('04/06/2020','10/07/2020'),'C',7,4,6);
INSERT INTO INFECTADOS_COVID VALUES (id_infectado_seq.nextval,historia('28/03/2020',null),'I',9,5,8);
INSERT INTO INFECTADOS_COVID VALUES (id_infectado_seq.nextval,historia('15/02/2020','11/04/2020'),'M',11,6,12);
INSERT INTO INFECTADOS_COVID VALUES (id_infectado_seq.nextval,historia('07/04/2020','10/05/2020'),'C',13,7,10);
INSERT INTO INFECTADOS_COVID VALUES (id_infectado_seq.nextval,historia('09/04/2020',null),'I',14,8,1);
INSERT INTO INFECTADOS_COVID VALUES (id_infectado_seq.nextval,historia('19/06/2020','01/07/2020'),'I',16,9,3);
INSERT INTO INFECTADOS_COVID VALUES (id_infectado_seq.nextval,historia('05/05/2020','20/06/2020'),'C',17,10,13);
INSERT INTO INFECTADOS_COVID VALUES (id_infectado_seq.nextval,historia('07/06/2020',null),'I',19,11,15);
INSERT INTO INFECTADOS_COVID VALUES (id_infectado_seq.nextval,historia('17/04/2020','28/05/2020'),'C',20,12,5);
INSERT INTO INFECTADOS_COVID VALUES (id_infectado_seq.nextval,historia('28/03/2020',null),'I',24,13,6);
INSERT INTO INFECTADOS_COVID VALUES (id_infectado_seq.nextval,historia('24/02/2020','01/04/2020'),'M',7,14,10);
INSERT INTO INFECTADOS_COVID VALUES (id_infectado_seq.nextval,historia('20/04/2020',null),'I',26,15,8;
INSERT INTO INFECTADOS_COVID VALUES (id_infectado_seq.nextval,historia('02/05/2020','30/05/2020'),'I',3,null,1);
INSERT INTO INFECTADOS_COVID VALUES (id_infectado_seq.nextval,historia('17/03/2020','21/05/2020'),'C',6,null,8);
INSERT INTO INFECTADOS_COVID VALUES (id_infectado_seq.nextval,historia('14/04/2020','24/06/2020'),'C',12,null,5);
INSERT INTO INFECTADOS_COVID VALUES (id_infectado_seq.nextval,historia('19/01/2020','27/02/2020'),'M',15,null,6);
INSERT INTO INFECTADOS_COVID VALUES (id_infectado_seq.nextval,historia('25/06/2020',null),'I',22,null,13);
