--Users
CREATE USER ADMIN_DB IDENTIFIED BY ADMIN_DB;
CREATE USER ADMIN_PS IDENTIFIED BY ADMIN_PS;
CREATE USER EMP_PS IDENTIFIED BY EMP_PS;
CREATE USER ADMIN_PG IDENTIFIED BY ADMIN_PG;
CREATE USER EMP_PG IDENTIFIED BY EMP_PG;
CREATE USER ADMIN_PI IDENTIFIED BY ADMIN_PI;
CREATE USER EMP_PI IDENTIFIED BY EMP_PI;
CREATE USER ADMIN_A IDENTIFIED BY ADMIN_A;
CREATE USER EMP_A IDENTIFIED BY EMP_A;